name: XP Tracker

on:
  workflow_dispatch:

jobs:
  run-xp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Rodar script
        run: python scripts/xp_calculator.py
